leaguebot:
  container_name: leaguebot
  build: .
  env_file:
      - .env
  dockerfile: docker/Dockerfile
  volumes:
      - .:/discord-bot
  ports:
      - "80:80"
  restart: alwaysbackup:
  container_name: backup
  build: .
  env_file:
      - .env
  dockerfile: docker/backup/Dockerfile
  external_links:
      - couchbase:db
  volumes:
      - /opt/docker/backup:/backup